./get_overall_reward.sh simple_push_2_1_uest_False_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_push_2_1_uest_False_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_push_2_1_uest_False_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_push_3_1_uest_False_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_push_3_1_uest_False_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_push_3_1_uest_False_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_push_3_2_uest_False_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_push_3_2_uest_False_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_push_3_2_uest_False_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_push_4_2_uest_False_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_push_4_2_uest_False_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_push_4_2_uest_False_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_push_2_1_uest_True_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_push_2_1_uest_True_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_push_2_1_uest_True_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_push_3_1_uest_True_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_push_3_1_uest_True_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_push_3_1_uest_True_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_push_3_2_uest_True_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_push_3_2_uest_True_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_push_3_2_uest_True_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_push_4_2_uest_True_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_push_4_2_uest_True_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_push_4_2_uest_True_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_tag_2_1_uest_False_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_tag_2_1_uest_False_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_tag_2_1_uest_False_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_tag_3_1_uest_False_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_tag_3_1_uest_False_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_tag_3_1_uest_False_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_tag_3_2_uest_False_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_tag_3_2_uest_False_indep_False_constr_True_expvar_ 2

./get_overall_reward.sh simple_tag_4_2_uest_False_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_tag_4_2_uest_False_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_tag_4_2_uest_False_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_tag_2_1_uest_True_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_tag_2_1_uest_True_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_tag_2_1_uest_True_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_tag_3_1_uest_True_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_tag_3_1_uest_True_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_tag_3_1_uest_True_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_tag_3_2_uest_True_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_tag_3_2_uest_True_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_tag_3_2_uest_True_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_tag_4_2_uest_True_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_tag_4_2_uest_True_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_tag_4_2_uest_True_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_adversary_2_1_uest_False_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_adversary_2_1_uest_False_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_adversary_2_1_uest_False_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_adversary_3_1_uest_False_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_adversary_3_1_uest_False_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_adversary_3_1_uest_False_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_adversary_3_2_uest_False_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_adversary_3_2_uest_False_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_adversary_3_2_uest_False_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_adversary_4_2_uest_False_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_adversary_4_2_uest_False_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_adversary_4_2_uest_False_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_adversary_2_1_uest_True_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_adversary_2_1_uest_True_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_adversary_2_1_uest_True_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_adversary_3_1_uest_True_indep_False_constr_False_none_ 1
./get_overall_reward.sh simple_adversary_3_1_uest_True_indep_False_constr_True_expvar_ 1
./get_overall_reward.sh simple_adversary_3_1_uest_True_indep_False_constr_True_cvar_ 1

./get_overall_reward.sh simple_adversary_3_2_uest_True_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_adversary_3_2_uest_True_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_adversary_3_2_uest_True_indep_False_constr_True_cvar_ 2

./get_overall_reward.sh simple_adversary_4_2_uest_True_indep_False_constr_False_none_ 2
./get_overall_reward.sh simple_adversary_4_2_uest_True_indep_False_constr_True_expvar_ 2
./get_overall_reward.sh simple_adversary_4_2_uest_True_indep_False_constr_True_cvar_ 2
