./get_overall_variance.sh simple_push_2_1_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_3_1_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_3_2_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_4_2_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_2_1_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_3_1_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_3_2_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_push_4_2_uest_True_indep_False_constr_False_none_ avg_var

./get_overall_variance.sh simple_tag_2_1_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_3_1_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_3_2_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_4_2_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_2_1_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_3_1_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_3_2_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_tag_4_2_uest_True_indep_False_constr_False_none_ avg_var

./get_overall_variance.sh simple_adversary_2_1_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_3_1_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_3_2_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_4_2_uest_False_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_2_1_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_3_1_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_3_2_uest_True_indep_False_constr_False_none_ avg_var
./get_overall_variance.sh simple_adversary_4_2_uest_True_indep_False_constr_False_none_ avg_var
